[package]
name = "braided_motion_planning"
version = "0.1.0"
edition = "2021"


[dependencies]
topo_spaces = {path = "../toppo/topo_spaces"}
alg = {path = "../toppo/alg"}
plotters = "*"
quasi_iter = "*"